-- dropping foreign keys
ALTER TABLE project DROP CONSTRAINT FK_TEAM_PROJECT;

ALTER TABLE users DROP CONSTRAINT FK_USER_CV;
ALTER TABLE users DROP CONSTRAINT FK_USER_PROJECT;

ALTER TABLE cv DROP CONSTRAINT FK_CV_USER;
ALTER TABLE cv DROP CONSTRAINT FK_CV_SENIORITY;

ALTER TABLE positions DROP CONSTRAINT FK_POSITION_PROJECT;
ALTER TABLE positions DROP CONSTRAINT FK_POSITION_SENIORITY;
ALTER TABLE positions DROP CONSTRAINT FK_POSITION_USER;

-- dropping foreign keys for many-to-many relationships
ALTER TABLE language_position DROP CONSTRAINT FK_LANG_POS_LANGUAGE;
ALTER TABLE language_position DROP CONSTRAINT FK_LANG_POS_POSITION;

ALTER TABLE language_cv DROP CONSTRAINT FK_LANG_CV_LANGUAGE;
ALTER TABLE language_cv DROP CONSTRAINT FK_LANG_CV_CV;

ALTER TABLE user_team DROP CONSTRAINT FK_USER_TEAM_USER;
ALTER TABLE user_team DROP CONSTRAINT FK_USER_TEAM_TEAM;

DROP TABLE languages;
DROP TABLE seniority;
DROP TABLE team;
DROP TABLE project;
DROP TABLE users;
DROP TABLE cv;
DROP TABLE positions;

-- dropping tables for many-to-many relationships
DROP TABLE language_position;
DROP TABLE language_cv;
DROP TABLE user_team;